<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;

    protected $guarded = [];

    public static function semua_akses()
    {
        $data = [
            'akses_daftar_jabatan' => 'Akses Daftar Jabatan',
            'akses_tambah_jabatan' => 'Akses Tambah Jabatan',
            'akses_edit_jabatan' => 'Akses Edit Jabatan',
            'akses_hapus_jabatan' => 'Akses Hapus Jabatan',
            'akses_daftar_user' => 'Akses Daftar User',
            'akses_tambah_user' => 'Akses Tambah User',
            'akses_edit_user' => 'Akses Edit User',
            'akses_hapus_user' => 'Akses Hapus User',
            'akses_daftar_akun' => 'Akses Daftar Akun',
            'akses_tambah_akun' => 'Akses Tambah Akun',
            'akses_edit_akun' => 'Akses Edit Akun',
            'akses_hapus_akun' => 'Akses Hapus Akun',
            'akses_daftar_jurnal' => 'Akses Daftar Jurnal Akuntansi',
            'akses_tambah_jurnal' => 'Akses Tambah Jurnal Akuntansi',
            // 'akses_edit_jurnal' => 'Akses Edit Jurnal Akuntansi',
            'akses_hapus_jurnal' => 'Akses Hapus Jurnal Akuntansi',
            'akses_daftar_gudang' => 'Akses Daftar Gudang',
            'akses_tambah_gudang' => 'Akses Tambah Gudang',
            'akses_edit_gudang' => 'Akses Edit Gudang',
            'akses_hapus_gudang' => 'Akses Hapus Gudang',
            'akses_daftar_satuan' => 'Akses Daftar Satuan',
            'akses_tambah_satuan' => 'Akses Tambah Satuan',
            'akses_edit_satuan' => 'Akses Edit Satuan',
            'akses_hapus_satuan' => 'Akses Hapus Satuan',
            'akses_daftar_kategori_barang' => 'Akses Daftar Kategori Barang',
            'akses_tambah_kategori_barang' => 'Akses Tambah Kategori Barang',
            'akses_edit_kategori_barang' => 'Akses Edit Kategori Barang',
            'akses_hapus_kategori_barang' => 'Akses Hapus Kategori Barang',
            'akses_daftar_barang' => 'Akses Daftar Barang',
            'akses_tambah_barang' => 'Akses Tambah Barang',
            'akses_edit_barang' => 'Akses Edit Barang',
            'akses_hapus_barang' => 'Akses Hapus Barang',
            'akses_daftar_transaksi_barang' => 'Akses Daftar Mutasi Barang',
            'akses_tambah_transaksi_barang' => 'Akses Tambah Mutasi Barang',
            'akses_edit_transaksi_barang' => 'Akses Edit Mutasi Barang',
            'akses_hapus_transaksi_barang' => 'Akses Hapus Mutasi Barang',
            'akses_edit_setting' => 'Akses Edit Setting',
            'akses_daftar_kontak' => 'Akses Daftar Kontak',
            'akses_tambah_kontak' => 'Akses Tambah Kontak',
            'akses_edit_kontak' => 'Akses Edit Kontak',
            'akses_hapus_kontak' => 'Akses Hapus Kontak',
            'akses_daftar_pembelian' => 'Akses Daftar Pembelian',
            'akses_tambah_pembelian' => 'Akses Tambah Pembelian',
            // 'akses_edit_pembelian' => 'Akses Edit Pembelian',
            'akses_hapus_pembelian' => 'Akses Hapus Pembelian',
            'akses_daftar_pelunasan_hutang' => 'Akses Daftar Pelunasan Hutang',
            'akses_tambah_pelunasan_hutang' => 'Akses Tambah Pelunasan Hutang',
            // 'akses_edit_pelunasan_hutang' => 'Akses Edit Pelunasan Hutang',
            'akses_hapus_pelunasan_hutang' => 'Akses Hapus Pelunasan Hutang',
            'akses_daftar_penjualan' => 'Akses Daftar Penjualan',
            'akses_tambah_penjualan' => 'Akses Tambah Penjualan',
            // 'akses_edit_penjualan' => 'Akses Edit Penjualan',
            'akses_hapus_penjualan' => 'Akses Hapus Penjualan',
            'akses_daftar_pelunasan_piutang' => 'Akses Daftar Pelunasan Piutang',
            'akses_tambah_pelunasan_piutang' => 'Akses Tambah Pelunasan Piutang',
            // 'akses_edit_pelunasan_piutang' => 'Akses Edit Pelunasan Piutang',
            'akses_hapus_pelunasan_piutang' => 'Akses Hapus Pelunasan Piutang',
            'akses_laporan_pembelian' => 'Akses Laporan Pembelian',
            // 'akses_laporan_pelunasan_hutang' => 'Akses Laporan Pelunasan Hutang',
            'akses_laporan_penjualan' => 'Akses Laporan Penjualan',
            // 'akses_laporan_pelunasan_piutang' => 'Akses Laporan Pelunasan Piutang',
            'akses_laporan_mutasi_barang' => 'Akses Laporan Mutasi Barang',
            'akses_buku_besar' => 'Akses Buku Besar',
            'akses_neraca' => 'Akses Neraca',
            'akses_laporan_laba_rugi' => 'Akses Laporan Laba Rugi',
            'akses_tutupan_laporan_laba_rugi' => 'Akses Tutupan Laporan Laba Rugi',
        ];
        return $data;
    }

    public static function semua_akses2()
    {
        $data = [
            'akses_daftar_jabatan',
            'akses_tambah_jabatan',
            'akses_edit_jabatan',
            'akses_hapus_jabatan',
            'akses_daftar_user',
            'akses_tambah_user',
            'akses_edit_user',
            'akses_hapus_user',
            'akses_daftar_akun',
            'akses_tambah_akun',
            'akses_edit_akun',
            'akses_hapus_akun',
            'akses_daftar_jurnal',
            'akses_tambah_jurnal',
            'akses_hapus_jurnal',
            'akses_daftar_gudang',
            'akses_tambah_gudang',
            'akses_edit_gudang',
            'akses_hapus_gudang',
            'akses_daftar_satuan',
            'akses_tambah_satuan',
            'akses_edit_satuan',
            'akses_hapus_satuan',
            'akses_daftar_kategori_barang',
            'akses_tambah_kategori_barang',
            'akses_edit_kategori_barang',
            'akses_hapus_kategori_barang',
            'akses_daftar_barang',
            'akses_tambah_barang',
            'akses_edit_barang',
            'akses_hapus_barang',
            'akses_daftar_transaksi_barang',
            'akses_tambah_transaksi_barang',
            'akses_edit_transaksi_barang',
            'akses_hapus_transaksi_barang',
            'akses_edit_setting',
            'akses_daftar_kontak',
            'akses_tambah_kontak',
            'akses_edit_kontak',
            'akses_hapus_kontak',
            'akses_daftar_pembelian',
            'akses_tambah_pembelian',
            // 'akses_edit_pembelian',
            'akses_hapus_pembelian',
            'akses_daftar_pelunasan_hutang',
            'akses_tambah_pelunasan_hutang',
            // 'akses_edit_pelunasan_hutang',
            'akses_hapus_pelunasan_hutang',
            'akses_daftar_penjualan',
            'akses_tambah_penjualan',
            // 'akses_edit_penjualan',
            'akses_hapus_penjualan',
            'akses_daftar_pelunasan_piutang',
            'akses_tambah_pelunasan_piutang',
            // 'akses_edit_pelunasan_piutang',
            'akses_hapus_pelunasan_piutang',
            'akses_laporan_pembelian',
            // 'akses_laporan_pelunasan_hutang',
            'akses_laporan_penjualan',
            // 'akses_laporan_pelunasan_piutang',
            'akses_laporan_mutasi_barang',
            'akses_buku_besar',
            'akses_neraca',
            'akses_laporan_laba_rugi',
            'akses_tutupan_laporan_laba_rugi',
        ];
        return $data;
    }
}
